// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Hero from './Hero';
import Image from './Image';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	CallToAction,
	Hero,
	Image,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	call_to_action: CallToAction,
	hero: Hero,
	image: Image,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
